FROM node:current-alpine

WORKDIR /app

COPY ./utils/bundlePackage.js ./
COPY ./utils/getBundleCode.js ./
COPY ./utils/getEntryPointPath.js ./
COPY ./docker-package.json ./package.json

RUN npm install

ENTRYPOINT ["node", "getBundleCode.js"]
