FROM node:current-alpine

WORKDIR /app

COPY ./bundlePackage.js ./
COPY ./getBundleCode.js ./
COPY ./getEntryPointPath.js ./
COPY ./docker-package.json ./package.json

CMD ["node", "getBundleCode.js"]

RUN npm install
